### ISSUE TITLE
KeyError: '_session_key'

### ISSUE THREAD

**Issue by kr1-s** [vypivshiy/findclone_api#1]
Взял код из примера, поменял логин и пасс, попробовал запустить и вылетает следующая ошибка.

```
Traceback (most recent call last):
  File "C:/Users/skriv/PycharmProjects/findclone_bot/test.py", line 14, in <module>
    f.login(phone, password)
  File "C:\Users\skriv\PycharmProjects\findclone_bot\venv\lib\site-packages\Findclone\Findclone.py", line 42, in login
    self._session_key = response.json()["_session_key"]
KeyError: '_session_key'
```

**Comment by vypivshiy** [comment]
> Взял код из примера, поменял логин и пасс, попробовал запустить и вылетает следующая ошибка.
> 
> ```
> Traceback (most recent call last):
>   File "C:/Users/skriv/PycharmProjects/findclone_bot/test.py", line 14, in <module>
>     f.login(phone, password)
>   File "C:\Users\skriv\PycharmProjects\findclone_bot\venv\lib\site-packages\Findclone\Findclone.py", line 42, in login
>     self._session_key = response.json()["_session_key"]
> KeyError: '_session_key'
> ```

Привет! Извиняюсь, что не так оперативно ответил. Проверил запрос, они изменили возвращаемый json объект.
Завез фикс, обновите модуль
